meta_product_name: "PersEd"
meta_title: "PersEd - The Ultimate Tools for Teachers"
meta_description: "PersEd delivers the tools that will make the evaluation process of your students smooth and neat. Send them the evaluation material and compare their progress."
meta_image: "fb_image.jpg" # should exist in `app/assets/images/`
twitter_account: "@mikeszymkat"
